In [16]:
import json
import pandas
import urllib.request
from pandas.io.json import json_normalize

URL = 'https://services.arcgis.com/su8ic9KbA7PYVxPS/arcgis/rest/services/HCPH_COVID19_Zip_Codes_download/FeatureServer/0/query?where=1%3D1&outFields=ZIP,TotalPop,TotalConfirmedCases,ActiveCases_str,Death_str,EditDate&returnGeometry=false&outSR=4326&f=json'

In [17]:
body = urllib.request.urlopen(URL).read()

In [18]:
parsed_body = json.loads(body)

In [21]:
df = pandas.json_normalize(parsed_body,record_path=['features'])

KeyError: 'attributes'

In [20]:
df

,attributes.ZIP,attributes.TotalPop,attributes.TotalConfirmedCases,attributes.ActiveCases_str,attributes.Death_str,attributes.EditDate
0,77003,9876,1048,31,13,2021/03/15
1,77004,36959,1891,55,28,2021/03/15
2,77006,22632,1274,31,0-5,2021/03/15
3,77007,37492,2824,86,7,2021/03/15
4,77013,20706,1467,55,13,2021/03/15
...,...,...,...,...,...,...
136,77396,57775,4717,177,34,2021/03/15
137,77450,73683,2756,167,22,2021/03/15
138,77493,32257,3551,180,52,2021/03/15
139,77494,114989,358,7,0-5,2021/03/15
140,77546,53320,906,47,7,2021/03/15